name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.1)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for changelog generation
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get version
      id: version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
    
    - name: Build binaries
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh ${{ steps.version.outputs.VERSION }}
    
    - name: Create checksums
      run: |
        cd dist
        sha256sum * > checksums.txt
    
    - name: Generate changelog
      id: changelog
      run: |
        # Get commits since last tag
        LAST_TAG=$(git tag --sort=-version:refname | head -n 2 | tail -n 1)
        if [ -z "$LAST_TAG" ]; then
          CHANGELOG="Initial release"
        else
          CHANGELOG=$(git log --oneline ${LAST_TAG}..HEAD --pretty=format:"- %s" | head -20)
        fi
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create or update tag
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Update version in source code
        sed -i 's/Version   = ".*"/Version   = "${{ steps.version.outputs.VERSION }}"/' internal/version/version.go
        
        # Commit and tag if there are changes
        if [ -n "$(git status --porcelain)" ]; then
          git add internal/version/version.go
          git commit -m "chore: bump version to ${{ steps.version.outputs.VERSION }}"
          git push origin main
        fi
        
        # Create tag
        git tag -a "v${{ steps.version.outputs.VERSION }}" -m "Release version ${{ steps.version.outputs.VERSION }}"
        git push origin "v${{ steps.version.outputs.VERSION }}"
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}
        name: Release ${{ steps.version.outputs.VERSION }}
        body: |
          ## What's Changed
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## Installation
          
          Download the appropriate binary for your platform:
          - **Linux AMD64**: `cngt-cli-linux-amd64`
          - **Linux ARM64**: `cngt-cli-linux-arm64`
          - **macOS AMD64**: `cngt-cli-darwin-amd64`
          - **macOS ARM64**: `cngt-cli-darwin-arm64`
          - **Windows**: `cngt-cli-windows-amd64.exe`
          
          ## Quick Install
          
          ### Linux/macOS
          ```bash
          # Download and install (replace with your platform)
          curl -sSL https://github.com/snupai/cngt-cli/releases/download/v${{ steps.version.outputs.VERSION }}/cngt-cli-linux-amd64 -o cngt-cli
          chmod +x cngt-cli
          sudo mv cngt-cli /usr/local/bin/
          ```
          
          ### Windows
          ```powershell
          # Download and place in PATH
          Invoke-WebRequest -Uri "https://github.com/snupai/cngt-cli/releases/download/v${{ steps.version.outputs.VERSION }}/cngt-cli-windows-amd64.exe" -OutFile "cngt-cli.exe"
          ```
          
          ## Verify Installation
          ```bash
          cngt-cli --version
          cngt-cli --help
          ```
        files: |
          dist/cngt-cli-windows-amd64.exe
          dist/cngt-cli-linux-amd64
          dist/cngt-cli-linux-arm64
          dist/cngt-cli-darwin-amd64
          dist/cngt-cli-darwin-arm64
          dist/checksums.txt
        draft: false
        prerelease: false